language: node_js
node_js:
  - 8
  - 7
  - 6
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache: yarn
notifications:
  webhooks:
    urls:
      - https://webhook.deux-tours-bus.com/travis/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
  slack:
    secure: Z9VZ7TM2B3D70xCvbCVH97AtfxZFQGfvITr2sZ5dslxkRAvkUTeGCVi6r/kPZVFw/GMXdE183jvDRZ6tva8bWbVKOeXbbmjMgWmTMxij46MevZXXEBNl6cL1mLur+BKyJ+mwqt66ndnXuakZSywazF5YiEZZqBhMoPlVCa+c/cImTdrWQsxNbi+wF3wMM2DN9I85O7SIdx3GturPyYBt05W3DgqJUOJhjBTNKXZAaCmrbhDA0Q9Dmyu2Y7ETuQ+u6APvOC8ARIgVs0PoaZ1hFaAOqMAyfgWKZhH2D++M44T5Fo+xHfP6xAANK3TXfxm7hvkPJS0ihrMUhsWIHfXUpJx4eugK2ec+p8SRj/tdv8Ivzy6MSPdcOLwgxWC1Nz1koYnqe0C/kUwtMBe79H8GIUua87knLNL3io2xhqbB4LB7UghUBBwPI4Z7JlIExP04MYINPjs9u3ROd0UW1yln7UBgs2s4IohbRkj5EbesJr1i0+P9NVBaJUpTNCDLYQslFraAG9AlLysk9dGqH8HSTZ5VoR9iw1MnBONw5DyxHT3T/d3rxy94irmj1Z7mA4MYGi7M0lp7teVIHDkpr/ohghyI67vEwvtz6NrFKK9L5wcXwVGfJvUR5f892J6q7tsMrSU5htk0kpJVUP6EbmUrnm7d0nvv9f1Tb7qTu6LfBTw=
    on_pull_requests: false
