on: pull_request

name: Deploy on Now (Staging)

jobs:
  build:
    name: Deploy and Alias with PR number
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Filters [opened, synchronize] for GitHub Actions
      uses: actions/bin/filter@3c0b4f0
      with:
        args: "action 'opened|synchronize'"

    - name: Debug on actions/bin
      run: env | sort -f

    - name: Extract pull_request.number
      id: pull_request_number
      run: jq -r '.number' ${GITHUB_EVENT_PATH}

    - name: Deploy2Staging
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          deploy
          --local-config=./now.json
          --env NODE_ENV=staging
          --public
          --no-clipboard
          > /github/home/Deploy2Staging.txt

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Debug on actions/zeit-now
      env:
        PULL_REQUEST_NUMBER: ${{ steps.pull_request_number }}
      run: echo ${PULL_REQUEST_NUMBER}

    - name: alias
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          alias
          `cat /github/home/Deploy2Staging.txt`
          bus-time-table-web-pr-${{ steps.pull_request_number.outputs }}.now.sh
