on: pull_request

name: Deploy on Now (Staging)

jobs:
  build:
    name: Deploy and Alias with PR number
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Filters [opened, synchronize] for GitHub Actions
      uses: actions/bin/filter@3c0b4f0
      with:
        args: "action 'opened|synchronize'"

    - name: Deploy2Staging
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          deploy
          --local-config=./now.json
          --env NODE_ENV=staging
          --public
          --no-clipboard
          > /github/home/Deploy2Staging.txt

    - name: alias
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          alias
          `cat /github/home/Deploy2Staging.txt`
          bus-time-table-web-pr-${{ github.event.number }}.now.sh
