on: pull_request

name: Deploy on Now (Staging)

jobs:
  build:
    name: Deploy and Alias with PR number
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Filters [opened, synchronize] for GitHub Actions
      uses: actions/bin/filter@3c0b4f0
      with:
        args: "action 'opened|synchronize'"

    - name: Extract pull_request.number
      run: |
        jq -r '.number' ${GITHUB_EVENT_PATH} > ${HOME}/pr-number.txt
        echo ${HOME}/pr-number.txt
        cat ${HOME}/pr-number.txt

    - name: Deploy2Staging
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          deploy
          --local-config=./now.json
          --env NODE_ENV=staging
          --public
          --no-clipboard
          > ${HOME}/Deploy2Staging.txt

    - name: alias
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          alias
          `cat ${HOME}/Deploy2Staging.txt`
          bus-time-table-web-pr-`cat ${HOME}/pr-number.txt`.now.sh

    - name: debug
      run: |
        echo ${HOME}/pr-number.txt
        cat ${HOME}/pr-number.txt
