on: pull_request

name: Deploy on Now (Staging)

jobs:
  filter_opened_or_synchronize:
    name: Filter pull-request opened or synchronize
    runs-on: ubuntu-latest

    steps:
    - name: Filters opened or synchronize
      uses: actions/bin/filter@3c0b4f0
      with:
        args: "action 'opened|synchronize'"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: filter_opened_or_synchronize

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Yarn-pkg
      run: npm install -g yarn

    - name: Versions
      run: |
        node --version
        npm --version
        yarn --version

    - name: Install packages
      run: yarn install --production --no-progress --non-interactive

    - name: Test
      run: yarn test

  deploy_on_zeit_now_staging:
    name: Deploy and Alias with PR number
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Deploy for staging
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          deploy
          --local-config=./now.json
          --build-env NODE_ENV=staging
          --env NODE_ENV=staging
          --public
          --no-clipboard
          > ${HOME}/deployment-url.txt

    - name: Alias with PR number
      uses: actions/zeit-now@5c51b26
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: >
          alias
          `cat ${HOME}/deployment-url.txt`
          bus-time-table-web-pr-${{ github.event.number }}.now.sh
